# Generated by Django 4.0.4 on 2022-04-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
